import os
from pathlib import Path

def generate_section2():
    sec2_tex = r"""
\section{Proposed Framework}
\label{sec:proposed_framework}

\subsection{Overall SPGRL Architecture}
The Semantic Predictive Graph Reinforcement Learning (SPGRL) framework proposes an end-to-end, multi-modal cyber-physical system designed to eliminate the inherent limitations of isolated traffic signal controllers. Rather than treating computer vision, spatial reasoning, sequence forecasting, and policy optimization as mathematically disjoint operations, the SPGRL architecture executes a continuous forward pass from raw visual pixel ingestion to optimal phase actuation. 

The complete sequential pipeline executes across the following topological flow:
\begin{verbatim}
Raw Traffic Video
        |
Offline VideoMAE
        |
  768-D Features
        |
  MULDE + GMM
        |
Semantic Anomaly (As)
        \
         \
YOLO + DeepSORT ----------> Behavioral Anomaly (Ab)
          \
           \
Historical Traffic -----------> LSTM ----------> (Ft)
            \
             \
Neighbor Graph ------------------> GNN ---------> (Gt)
              \
               \
Carbon Engine ----------------------> (Ct)
                \
                 \
Emergency Routing --------------------> (Et)
                  \
                   \
             Unified State (Zt)
                     |
              Multi-Agent PPO
                     |
               Safety Shield
                     |
              Signal Control
\end{verbatim}

This macroscopic architecture encapsulates eight distinct functional layers operating in synchrony. The sensing layer ingests unconstrained raw telemetry. The perception layer resolves this into discrete kinematic and semantic identifiers. The prediction layer maps the temporal horizon, while the graph layer establishes spatial interconnectivity. The sustainability and emergency layers project auxiliary environmental and priority constraints. Finally, the decision layer computes the optimal phase transition, strictly gated by an absolute deterministic safety layer ensuring physical compliance.

\subsection{Layered Architecture}
To guarantee modular fault tolerance and scalable execution, the SPGRL stack is constructed as a strictly hierarchical layered architecture. 

\textbf{Layer 1: Traffic Sensing Layer.} The foundational stratum ingests heterogeneous raw data. Inputs include unconstrained surveillance video streams and induction loop arrays. The primary computational role is raw data synchronization and metadata tagging, providing an isolated temporal foundation for all upstream networks.

\textbf{Layer 2: Semantic Perception Layer.} Operating on the visual stream, this layer isolates latent anomalies that lack explicit geometric boundaries (e.g., debris, weather disruption, ambient gridlock). By employing advanced autoencoders and density estimators, it maps raw pixels into compressed, highly discriminative internal representations, explicitly outputting a continuous semantic severity score.

\textbf{Layer 3: Behavioral Perception Layer.} Parallel to semantic evaluation, this layer executes explicit object tracking. It bounds physical entities and computes kinematic divergences such as hard braking or wrong-way traversal. The output is a rigid behavioral anomaly index that complements the implicit semantic representations.

\textbf{Layer 4: Temporal Prediction Layer.} Dependent on historical state matrices generated by the sensing layer, the temporal prediction sequence network projects future volume and queue trajectories. Its computational role is to shift the RL policy from reactive lagging indicators to proactive horizon planning.

\textbf{Layer 5: Spatial Graph Reasoning Layer.} Intersections do not exist in a vacuum. This layer encodes the physical city topology as a directed graph, embedding intersection states into shared hidden vectors. It provides the downstream decision layer with localized awareness of incoming traffic shockwaves from neighboring nodes.

\textbf{Layer 6: Carbon Optimization Layer.} This analytical module translates physical acceleration and volume parameters into instantaneous emission metrics. It forces environmental sustainability directly into the optimization penalty manifold.

\textbf{Layer 7: Emergency Routing Layer.} A strictly deterministic routing engine operating independently of neural hallucination. It identifies priority vehicles and calculates absolute pathfinding overrides, passing a boolean emergency state to the decision nodes.

\textbf{Layer 8: Unified State Construction Layer.} The critical synchronization barrier. This layer polls the asymmetric asynchronous outputs from Layers 2 through 7 and concatenates them into a singular, ultra-dense multidimensional state tensor.

\textbf{Layer 9: Multi-Agent Decision Layer.} The core reinforcement learning policy. Driven by the unified state, decentralized actors execute continuous optimization, heavily constrained by a joint learning mechanism designed to resolve conflicting modal rewards.

\textbf{Layer 10: Safety Shield Layer.} A hard physical invariant constraint matrix. It serves as the final arbiter of execution, intercepting any proposed signal phase that violates spatial conflict boundaries or minimum statutory green times.

\subsection{Module Dependency Graph}
The execution stability of the SPGRL framework relies on a directed acyclic module dependency graph. 

The semantic stream relies on a strict cascade: VideoMAE ingests raw frames to produce latent features, which MULDE requires to compute denoising score gradients, which the GMM utilizes to calibrate the final $A_s$ output. The behavioral stream mandates that YOLO bounding box coordinates propagate directly to DeepSORT tracking filters to establish the kinematic $A_b$ divergence. 

Simultaneously, historical inductive loop data flows into the LSTM to compute the future trajectory $F_t$ and its variance-based confidence $C_f$. Road adjacency matrices initialize the GNN to perform spatial message passing resulting in the $G_t$ embedding. Real-time kinematic telemetry informs the Carbon Engine ($C_t$) and Emergency detection routines ($E_t$). 

Synchronization is critical. The upstream neural networks operate asynchronously on disparate temporal frequencies. The unified state constructor must resolve these latent dependencies, caching the most recent visual anomaly inferences while continuously polling the high-frequency numerical loops, ensuring the downstream RL agent never experiences observational starvation.

\subsection{Unified State Construction Overview}
Traditional deep reinforcement learning interventions in traffic signal control fundamentally fail when subjected to catastrophic physical anomalies. Legacy systems restrict their observation space exclusively to queue lengths, instantaneous occupancy, speed telemetry, or graph matrices. Consequently, when a physical collision halts traffic, the numerical loop sensors register zero flow. A traditional unimodal RL agent erroneously perceives this as an empty, optimal road and subsequently routes massive platoons directly into the hazard zone.

The SPGRL framework rectifies this through the construction of the Unified State ($Z_t = [G_t, A_s, A_b, F_t, C_f, C_t, E_t]$). By explicitly expanding the Markov state, the agent is granted direct observable evidence of the physical domain. The topological embedding ($G_t$) provides spatial context. The semantic ($A_s$) and behavioral ($A_b$) variables provide quantifiable visual disruption metrics. The prediction vector ($F_t$) and its confidence ($C_f$) bound the horizon. The carbon ($C_t$) and emergency ($E_t$) indicators append explicit penalty constraints. By fusing these modalities, the agent correctly correlates stagnant numerical flow with high visual anomaly severity, inherently learning to detour platoons.

\subsection{Training and Inference Pipeline}
The SPGRL pipeline requires a rigorous bifurcation between training and inference execution. 

During the offline training phase, the computationally heavy perception networks (VideoMAE, YOLO, DeepSORT) and structural networks (LSTM, GNN) extract latent representations stored in cached replay buffers. The Multi-Agent Proximal Policy Optimization (MAPPO) architecture employs Centralized Training with Decentralized Execution (CTDE). A centralized critic leverages the complete global joint state to compute robust advantage estimates, while decentralized actors optimize localized policies. Crucially, a joint optimization mechanism enforces gradient similarity, preventing catastrophic interference where updating the PPO actor degrades the upstream GNN or LSTM feature encoders.

During online inference, the architecture shifts to a streamlined forward pass. The physical camera initiates the sequence. Data cascades parallelly through the semantic perception, predictive, graph, carbon, and emergency layers. The outputs synchronize into the unified state vector ($Z_t$). The decentralized MAPPO actor natively processes this vector to propose a discrete signal phase. The deterministic safety shield evaluates the phase, and upon validation, the hardware controller executes the signal transition. 

\subsection{Safety-Critical Operation Pipeline}
Autonomous infrastructure mandates absolute resilience against stochastic failures. The SPGRL execution pipeline transitions seamlessly across distinct operational modes based on real-time severity classification.

In normal traffic mode, visual severities are low, and the agent primarily optimizes volume throughput and graph coordination. Upon detecting a collision, the system transitions to anomaly mode, where the elevated severity vector forces the RL policy to enact evasive routing. If the LSTM detects massive distributional shifts, prediction uncertainty mode is triggered, heavily penalizing reliance on the predictive temporal horizon.

During off-peak hours, the controller naturally falls back into carbon optimization mode, favoring long, uninterrupted arterial green waves to prevent heavy vehicular idling. Conversely, if an ambulance enters the local topology, the framework triggers emergency mode. The RL policy is instantaneously bypassed, and deterministic green-wave preemption is enforced. Finally, if the neural network hallucinates a conflicting phase, the system collapses into safety override mode, intercepting the command via the safety shield and executing a standard all-red clearance phase to guarantee absolute physical safety.
"""
    
    project_root = Path(__file__).resolve().parents[0]
    path = project_root / "SPGRL_IEEE_FINAL_MANUSCRIPT.tex"
    
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Remove \end{document}
    content = content.replace(r"\end{document}", "")
    
    # Append the new section
    content += sec2_tex
    content += "\n\\end{document}\n"
    
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

if __name__ == "__main__":
    generate_section2()
